import type { Metadata } from "next";

import "./globals.css";
import Navbar from "@/components/Navbar";
import SessionWrapper from "@/components/SessionWrapper";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "E-Gallery",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionWrapper>
      <html lang="en">
        <body>
          <div className="max-h-[5vh] ">
            <Navbar />
          </div>
          <div className="h-[95vh] pt-[6vh] ">{children}</div>
          <Toaster richColors />
        </body>
      </html>
    </SessionWrapper>
  );
}
